version: '3.8'
services:
  nextjs:
    build: ./OpenLAB-Web-FE
    container_name: nextjs
    image: nextjs:latest
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: always

networks:
  app-network:
    driver: bridge