FROM nginx:alpine

# Sao chép file cấu hình Nginx vào container
COPY nginx.conf /etc/nginx/nginx.conf

# Cài đặt certbot và các gói cần thiết
RUN apk add --no-cache certbot certbot-nginx openssl

# Lệnh khởi động Nginx
CMD ["nginx", "-g", "daemon off;"]
