version: '3'
services:
  openlab_fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - openlab_fe
