version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    expose:
      - "80"
      - "443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - certbot
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./webroot:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'certbot certonly --webroot -w /var/lib/letsencrypt -d openlab.com.vn && cp -r /etc/letsencrypt /var/lib/letsencrypt'"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
    networks:
      - web

networks:
  web:
    driver: bridge
