version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
